### ISSUE TITLE
I cannot change my login from an old Alby login I used.

### ISSUE THREAD

**Issue by mariaa144** [Jared-Dahlke/localsats#42] opened 2023-08-06 15:32 UTC
I have a problem where I want to login from another computer but I cannot because I cannot export my Alby keys from another computer.

Ideally, I could also login using email and password or allow multiple lightning node logins for the same account. This is because I cannot get the same keys on another computer to sign in at the moment.

See: https://github.com/getAlby/lightning-browser-extension/issues/2637

A workaround would be to delete my current account and start over, but I also cannot figure out how to delete and account I've created.

**Comment by Jared-Dahlke** [comment] 2023-08-07 00:09
> I have a problem where I want to login from another computer but I cannot because I cannot export my Alby keys from another computer.
> 
> 
> 
> Ideally, I could also login using email and password or allow multiple lightning node logins for the same account. This is because I cannot get the same keys on another computer to sign in at the moment.
> 
> 
> 
> See: https://github.com/getAlby/lightning-browser-extension/issues/2637
> 
> 
> 
> A workaround would be to delete my current account and start over, but I also cannot figure out how to delete and account I've created.

Hey sorry you're having this problem. Currently the only way to login is with your specific lightning wallet. So kind of like bitcoin, if you lose your keys or for whatever reason cant sign with your wallet, then you are out of luck. Your best bet is to login with a new lightning wallet , send a message to your other order , and after 14 days that order will get deleted . Just create a new order on your new lightning wallet. Are you sure you can't access Alby from other computer by logging in with Alby master password ?

Also if someone wants to create a pr that has a button once you're logged in that lets you assign another wallet to your account that shouldn't be too hard. I might look into it

**Comment by mariaa144** [comment] 2023-08-07 00:32
I didn't see where I could export my key on Alby. I think it is a bug which I reported on Alby.

Don't worry about the issue for me. I already have created a new account and will delete my offers on the old account.

**Comment by Jared-Dahlke** [comment] 2023-08-07 00:50
Ok cool. Closing this ticket . feel free to post again if you run into any issues or have any feature requests. Cheers

**Comment by Jared-Dahlke** [comment] 2023-08-07 19:08
closing due to:
I cannot help you if you lose your wallet keys! I do not have admin keys and couldn't help you even if i wanted to. This is a feature, not a bug. It helps you stay private

**Closed as completed by Jared-Dahlke** 2023-08-07 19:08 UTC
Labels: wontfix

**Comment by mariaa144** [comment] 2023-08-08 19:31
I was given instructions on how to get my old lnurl auth back but when I tried to login I got a different account name. I would have expected to get the old account name and account when I logged in.

I had to use the Lndhub connector to get my old lnurl auth back.

Do you know what might be the problem?
